chore(build): Fix transform error on node@0.12
https://travis-ci.org/moqada/dacho/jobs/91604000

```
/home/travis/build/moqada/dacho/src/Dacho.js:16
var Dacho = class Dacho {
            ^^^^^
Unexpected reserved word
  src/Dacho.js:16
  var Dacho = class Dacho {
              ^^^^^
  SyntaxError: Unexpected reserved word
      at exports.runInThisContext (vm.js:73:16)
      at loader (node_modules/babel-core/node_modules/babel-register/lib/node.js:128:5)
      at Object.require.extensions.(anonymous function) [as .js] (node_modules/babel-core/node_modules/babel-register/lib/node.js:138:7)
      at Object.<anonymous> (src/index.js:8:14)
      at loader (node_modules/babel-core/node_modules/babel-register/lib/node.js:128:5)
      at Object.require.extensions.(anonymous function) [as .js] (node_modules/babel-core/node_modules/babel-register/lib/node.js:138:7)
      at Context.<anonymous> (index-spec.js:9:18)
```